- block:
  - name: Assert if the snapshot already exists
    assert:
      that:
        - "snapshot_id is not defined"
      msg: "Snapshot {{ snapshot_name }} already exists. Quitting."

  - include_tasks: vm_shutdown.yml

  - include_tasks: snapshot_create.yml

  - include_tasks: vm_start.yml

  delegate_to: localhost
