---
- name: Create snapshot
  uri:
    url: "{{ manageiq_vm_resource.href }}/snapshots"
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
    method: POST
    body_format: json
    body:
      name: "{{ snapshot_name }}"
      description: "{{ snapshot_name }}"
      memory: false

- name: Wait for snapshot to be created
  uri:
    url: "{{ manageiq_vm_resource.href }}/snapshots/?expand=resources&filter[]=name={{ snapshot_name | regex_replace(' ', '%20') }}"
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
    method: GET
  register: manageiq_vm_snapshot_resources_json
  until: manageiq_vm_snapshot_resources_json.json.subcount == 1
  retries: 60
  delay: 15
