---
- name: Start vm
  uri:
    url: "{{ manageiq_vm_resource.href }}"
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
    method: POST
    body_format: json
    body:
      action: start
  when:
    - "snapshot_mode == 'cold'"

- name: Wait for VM to be on
  uri:
    url: "{{ manageiq_vm_resource.href }}?expand=resources"
    validate_certs: false
    headers:
      X-Auth-Token: "{{ manageiq.api_token }}"
    method: GET
  register: manageiq_vm_resource_json
  until: "manageiq_vm_resource_json.json.power_state == 'on'"
  retries: 60
  delay: 15

- name: Wait for host to be reachable
  wait_for_connection:
    timeout: 900
    delay: 15
